/*
 Akra Javascript Preprocessor:
 Copyright (C) 2011-2012 Akra Engine <akra@odserve.org>

 Esprima:
 Copyright (C) 2011 Ariya Hidayat <ariya.hidayat@gmail.com>

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright
 notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in the
 documentation and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 PREPROCESSOR VER.: 1.0.4
 */

function m(U){throw U;}var t=void 0,z=!0,I=null,R=!1;
(function(U){function V(a){return 0<="0123456789".indexOf(a)}function ea(a){return" "===a||"\t"===a||"\x0B"===a||"\u000c"===a||"\u00a0"===a||"\ufeff"===a}function S(a){return"\n"===a||"\r"===a||"\u2028"===a||"\u2029"===a}function $(a){return"$"===a||"_"===a||"a"<=a&&"z">=a||"A"<=a&&"Z">=a}function f(){var a="\x00",b=n;b<C&&(a=y[b],n+=1);return a}function N(){var a,b,d;for(d=b=R;n<C;)if(a=y[n],d)f(),S(a)&&(d=R,r+=1);else if(b)f(),"*"===a?(a=y[n],"/"===a&&(f(),b=R)):S(a)&&(r+=1);else if("/"===a)if(a=
y[n+1],"/"===a)f(),f(),d=z;else if("*"===a)f(),f(),b=z;else break;else if(ea(a))f();else if(S(a))f(),r+=1;else break}function ha(){var a=y[n],b,d,e;if(";"===a||"{"===a||"}"===a)return f(),{type:o.e,value:a};if(","===a||"("===a||")"===a)return f(),{type:o.e,value:a};b=y[n+1];if("."===a&&!V(b))return{type:o.e,value:f()};d=y[n+2];e=y[n+3];if(">"===a&&">"===b&&">"===d&&"="===e)return f(),f(),f(),f(),{type:o.e,value:">>>="};if("="===a&&"="===b&&"="===d)return f(),f(),f(),{type:o.e,value:"==="};if("!"===
a&&"="===b&&"="===d)return f(),f(),f(),{type:o.e,value:"!=="};if(">"===a&&">"===b&&">"===d)return f(),f(),f(),{type:o.e,value:">>>"};if("<"===a&&"<"===b&&"="===d)return f(),f(),f(),{type:o.e,value:"<<="};if(">"===a&&">"===b&&"="===d)return f(),f(),f(),{type:o.e,value:">>="};if("="===b&&0<="<>=!+-*%&|^/".indexOf(a))return f(),f(),{type:o.e,value:a+b};if(a===b&&0<="+-<>&|".indexOf(a)&&0<="+-<>&|".indexOf(b))return f(),f(),{type:o.e,value:a+b};if(0<="[]<>+-*%&|^!~?:=/".indexOf(a))return{type:o.e,value:f()}}
function X(){var a="",b,d,e,h;d=R;D=I;N();b=y[n];if("/"===b){for(a=f();n<C;)if(b=f(),a+=b,d)"]"===b&&(d=R);else{"\\"===b&&(a+=f());if("/"===b)break;"["===b&&(d=z);S(b)&&s(F.Oa,r)}d=a.substr(1,a.length-2);for(e="";n<C;){b=y[n];if(!($(b)||"0"<=b&&"9">=b))break;e+=b;a+=f()}try{h=RegExp(d,e)}catch(g){s(F.Ga,r)}return{Sa:a,value:h}}}function ia(){var a;if(n>=C)return{type:o.t};a=ha();if("undefined"!==typeof a)return a;a=y[n];if("'"===a||'"'===a){var b;var d="";a=y[n];if(!("'"!==a&&'"'!==a)){for(f();n<
C;)if(b=f(),b===a){a="";break}else"\\"===b?(b=f(),S(b)||(d+="\\",d+=b)):d+=b;""!==a&&s(F.U,r,"ILLEGAL");b={type:o.L,value:d}}return b}if("."===a||V(a)){a:if(b=y[n],V(b)||"."===b){d="";if("."!==b){d=f();b=y[n];if("x"===b||"X"===b){for(d+=f();n<C;){b=y[n];if(!(0<="0123456789abcdefABCDEF".indexOf(b)))break;d+=f()}d={type:o.w,value:parseInt(d,16)};break a}for(;n<C;){b=y[n];if(!V(b))break;d+=f()}}if("."===b)for(d+=f();n<C;){b=y[n];if(!V(b))break;d+=f()}if("e"===b||"E"===b)if(d+=f(),b=y[n],"+"===b||"-"===
b||V(b))for(d+=f();n<C;){b=y[n];if(!V(b))break;d+=f()}else s(F.U,r,"ILLEGAL");d={type:o.w,value:parseFloat(d)}}return d}d=y[n];if($(d)){for(b=f();n<C;){d=y[n];if(!($(d)||"0"<=d&&"9">=d))break;b+=f()}if(1===b.length)b={type:o.a,value:b};else{b:{switch(b){case "break":case "case":case "catch":case "continue":case "debugger":case "default":case "delete":case "do":case "else":case "finally":case "for":case "function":case "if":case "in":case "instanceof":case "new":case "return":case "switch":case "this":case "throw":case "try":case "typeof":case "var":case "void":case "while":case "with":case "class":case "const":case "enum":case "export":case "extends":case "import":case "super":case "implements":case "interface":case "let":case "package":case "private":case "protected":case "public":case "static":case "yield":d=
z;break b}d=R}b=d?{type:o.v,value:b}:"null"===b?{type:o.ia}:"true"===b||"false"===b?{type:o.Z,value:b}:{type:o.a,value:b}}a=b}else a=t;if("undefined"!==typeof a)return a;s(F.U,r,"ILLEGAL")}function k(){var a,b;if(D)return n=D.f[1],r=D.lineNumber,b=D,D=I,b;D=I;N();a=n;b=ia();b.f=[a,n];b.lineNumber=r;return b}function K(){var a,b,d;if(D!==I)return D;a=n;b=r;d=k();n=a;r=b;return D=d}function aa(){var a,b,d;a=n;b=r;N();d=r!==b;n=a;r=b;return d}function s(a,b){var d=Array.prototype.slice.call(arguments,
2);m(Error("Line "+b+": "+a.replace(/%(\d)/g,function(a,b){return d[b]||""})))}function H(a){a.type===o.t&&s(F.Ja,r);a.type===o.w&&s(F.La,r);a.type===o.L&&s(F.Na,r);a.type===o.a&&s(F.Ka,r);a.type===o.v&&s(F.Ma,r);a=a.value;10<a.length&&(a=a.substr(0,10)+"...");s(F.U,r,a)}function p(a){var b=k();(b.type!==o.e||b.value!==a)&&H(b)}function w(a){var b=k();(b.type!==o.v||b.value!==a)&&H(b)}function i(a){var b=K();return b.type===o.e&&b.value===a}function u(a){var b=K();return b.type===o.v&&b.value===a}
function ba(a){return a.type===e.a||a.type===e.o||a.type===e.k||a.type===e.Q}function G(){var a;";"===y[n]?k():(a=r,N(),r===a&&(i(";")?k():(a=K(),a.type!==o.t&&!i("}")&&H(a))))}function L(){var a;if(i("[")){a=[];for(p("[");n<C;){if(i("]")){k();break}if(i(","))k(),a.push(t);else{a.push(j());if(i("]")){k();break}p(",")}}return{type:e.C,elements:a}}if(i("{")){var b=[],d;for(p("{");n<C;){a=k();if(a.type===o.e&&"}"===a.value)break;d={};switch(a.type){case o.a:d.key={type:e.a,name:a.value};if("get"===a.value&&
!i(":")){a=k();a.type!==o.a&&H(a);p("(");p(")");d={key:{type:e.a,name:a.value},value:{type:e.n,id:I,p:[],body:x()},P:"get"};break}if("set"===a.value&&!i(":")){a=k();a.type!==o.a&&H(a);d.key={type:e.a,name:a.value};p("(");a=k();a.type!==o.a&&H(a);p(")");d.value={type:e.n,id:I,p:[{type:e.a,name:a.value}],body:x()};d.P="set";break}p(":");d.value=j();break;case o.L:case o.w:d.key={type:e.g,value:a.value};p(":");d.value=j();break;default:H(a)}b.push(d);a=K();if(a.type===o.e&&"}"===a.value){k();break}p(",")}return{type:e.R,
Aa:b}}if(i("("))return k(),a=v(),p(")"),a.b;if(u("function")){a=I;b=[];w("function");i("(")||(d=k(),d.type!==o.a&&H(d),a={type:e.a,name:d.value});p("(");if(!i(")"))for(;n<C;){d=k();d.type!==o.a&&H(d);b.push({type:e.a,name:d.value});if(i(")"))break;p(",")}p(")");d=x();return{type:e.n,id:a,p:b,body:d}}if(u("this"))return k(),{type:e.la};if(i("/")||i("/="))return{type:e.g,value:X().value};a=k();return a.type===o.a?{type:e.a,name:a.value}:a.type===o.Z?{type:e.g,value:"true"===a.value}:a.type===o.ia?{type:e.g,
value:I}:a.type===o.w?{type:e.g,value:a.value}:a.type===o.L?{type:e.g,value:a.value}:H(a)}function ca(){return L()}function da(){var a=[];p("(");if(!i(")"))for(;n<C;){a.push(j());if(i(")"))break;p(",")}p(")");return a}function la(){var a,b,d;if(a=u("new"))k(),b=la();else{var h;for(b=ca();n<C;)if(i("."))k(),h=k(),h.type!==o.a&&H(h),h={type:e.a,name:h.value},b={type:e.o,W:R,object:b,d:h};else if(i("["))k(),h=v(),h.type===e.H&&(h=h.b),b={type:e.o,W:z,object:b,d:h},p("]");else if(i("("))b={type:e.k,callee:b,
arguments:da()};else break}i("(")&&(d=da());return a?("undefined"===typeof d&&(d=[]),b.type===e.k&&(d=b.arguments,b=b.callee),{type:e.Q,callee:b,arguments:d}):"undefined"!==typeof d?{type:e.k,callee:b,arguments:d}:b}function M(){var a,b;if(i("++")||i("--"))return a=k().value,b=M(),ba(b)||s(F.Fa,r),{type:e.N,c:a,h:b,prefix:z};if(i("+")||i("-")||i("~")||i("!"))a={type:e.M,c:k().value,h:M()};else if(u("delete")||u("void")||u("typeof"))a={type:e.M,c:k().value,h:M()};else if(a=la(),(i("++")||i("--"))&&
!aa())ba(a)||s(F.Ea,r),a={type:e.N,c:k().value,h:a,prefix:R};return a}function ma(){for(var a=M();i("*")||i("/")||i("%");)a={type:e.j,c:k().value,left:a,right:M()};return a}function fa(){for(var a=ma();i("+")||i("-");)a={type:e.j,c:k().value,left:a,right:ma()};return a}function c(){var a;for(a=fa();i("<<")||i(">>")||i(">>>");)a={type:e.j,c:k().value,left:a,right:fa()};i("<")||i(">")||i("<=")||i(">=")?a={type:e.j,c:k().value,left:a,right:c()}:u("in")?(k(),a={type:e.j,c:"in",left:a,right:c()}):u("instanceof")&&
(k(),a={type:e.j,c:"instanceof",left:a,right:c()});return a}function Y(){for(var a=c();i("==")||i("!=")||i("===")||i("!==");)a={type:e.j,c:k().value,left:a,right:c()};return a}function ja(){for(var a=Y();i("&");)k(),a={type:e.j,c:"&",left:a,right:Y()};return a}function W(){for(var a=ja();i("|");)k(),a={type:e.j,c:"|",left:a,right:ja()};return a}function ka(){for(var a=W();i("^");)k(),a={type:e.j,c:"^",left:a,right:W()};return a}function na(){for(var a=ka();i("&&");)k(),a={type:e.J,c:"&&",left:a,right:ka()};
return a}function j(){var a;for(a=na();i("||");)k(),a={type:e.J,c:"||",left:a,right:na()};i("?")&&(k(),a={type:e.aa,test:a},a.r=j(),p(":"),a.z=j());var b=K(),d=b.value;if(b.type!==o.e?0:"="===d||"*="===d||"/="===d||"%="===d||"+="===d||"-="===d||"<<="===d||">>="===d||">>>="===d||"&="===d||"^="===d||"|="===d)ba(a)||s(F.Ca,r),a={type:e.D,c:k().value,left:a,right:j()};return a}function v(){var a=j();if(i(","))for(a={type:e.S,sa:[a]};n<C&&i(",");)k(),a.sa.push(j());return{type:e.H,b:a}}function x(){p("{");
for(var a=[],b;n<C&&!i("}");){b=A();if("undefined"===typeof b)break;a.push(b)}p("}");return{type:e.Y,body:a}}function J(){var a,b;a=k();a.type!==o.a&&H(a);a={type:e.a,name:a.value};b=I;i("=")&&(k(),b=j());return{id:a,B:b}}function oa(){for(var a=[];n<C;){a.push(J());if(!i(","))break;k()}return a}function h(){var a,b=I;w("continue");if(";"===y[n])return k(),{type:e.G,label:I};if(aa())return{type:e.G,label:I};a=K();a.type===o.a&&(k(),b={type:e.a,name:a.value});G();return{type:e.G,label:b}}function l(){var a,
b=I;w("break");if(";"===y[n])return k(),{type:e.F,label:I};if(aa())return{type:e.F,label:I};a=K();a.type===o.a&&(k(),b={type:e.a,name:a.value});G();return{type:e.F,label:b}}function q(){var a,b=I;w("return");if(" "===y[n]&&$(y[n+1]))return b=v().b,G(),{type:e.K,h:b};if(aa())return{type:e.K,h:I};i(";")||(a=K(),!i("}")&&a.type!==o.t&&(b=v().b));G();return{type:e.K,h:b}}function ga(){for(var a=[],b;n<C&&!i("}")&&!u("default")&&!u("case");){b=A();if("undefined"===typeof b)break;a.push(b)}return a}function A(){var a=
K(),b;if(a.type!==o.t){if(a.type===o.e)switch(a.value){case ";":return p(";"),{type:e.da};case "{":return x();case "(":return b=v(),G(),b}if(a.type===o.v)switch(a.value){case "break":return l();case "continue":return h();case "debugger":return w("debugger"),G(),{type:e.ba};case "do":var d;w("do");b=A();w("while");p("(");d=v().b;p(")");G();return{type:e.ca,body:b,test:d};case "for":var g,c,j;g=c=a=I;w("for");p("(");if(i(";"))k();else if(u("var")||u("let")?(g=k().value,g={type:e.O,X:oa(),P:g},u("in")&&
(k(),b=g,d=v().b,g=I)):g=v().b,"undefined"===typeof b)g.hasOwnProperty("operator")&&"in"===g.c?(b=g.left,d=g.right,g=I,ba(b)||s(F.Da,r)):p(";");if("undefined"===typeof b&&(i(";")||(c=v().b),p(";"),!i(")")))a=v().b;p(")");j=A();return"undefined"===typeof b?{type:e.fa,B:g,test:c,update:a,body:j}:{type:e.ea,left:b,right:d,body:j,Xa:R};case "if":return w("if"),p("("),b=v().b,p(")"),d=A(),u("else")?(k(),c=A()):c=I,{type:e.ga,test:b,r:d,z:c};case "let":return w("let"),b=oa(),G(),{type:e.O,X:b,P:"let"};
case "return":return q();case "switch":w("switch");p("(");b=v().b;p(")");p("{");if(i("}"))k(),b={type:e.T,ra:b};else{for(d=[];n<C&&!i("}");)u("default")?(k(),c=I):(w("case"),c=v().b),p(":"),d.push({type:e.ka,test:c,r:ga()});p("}");b={type:e.T,ra:b,va:d}}return b;case "throw":return w("throw"),aa()&&s(F.Ha,r),b=v().b,G(),{type:e.ma,h:b};case "try":return d=[],a=I,w("try"),b=x(),u("catch")&&(k(),p("("),i(")")||(c=v().b),p(")"),d.push({type:e.$,ya:c,Qa:I,body:x()})),u("finally")&&(k(),a=x()),0===d.length&&
!a&&s(F.Ia,r),{type:e.na,ua:b,Ra:d,wa:a};case "var":return w("var"),b=oa(),G(),{type:e.O,X:b,P:"var"};case "while":return w("while"),p("("),b=v().b,p(")"),d=A(),{type:e.oa,test:b,body:d};case "with":return w("with"),p("("),b=v().b,p(")"),d=A(),{type:e.pa,object:b,body:d}}b=v();if(b.b.type===e.n&&b.b.id!==I)return{type:e.I,id:b.b.id,p:b.b.p,body:b.b.body};if(b.b.type===e.a&&i(":"))return k(),{type:e.ha,label:b.b,body:A()};G();return b}}function O(){var a,b,d,e,h;a="";for(h=e=R;n<C;)if(b=y[n],h)b=f(),
S(b)?(h=R,r+=1,B.A.push({f:[d,n-1],type:"Line",value:a}),a=""):a+=b;else if(e)b=f(),a+=b,"*"===b?(b=y[n],"/"===b&&(a=a.substr(0,a.length-1),e=R,f(),B.A.push({f:[d,n-1],type:"Block",value:a}),a="")):S(b)&&(r+=1);else if("/"===b)if(b=y[n+1],"/"===b)d=n,f(),f(),h=z;else if("*"===b)d=n,f(),f(),e=z;else break;else if(ea(b))f();else if(S(b))f(),r+=1;else break;0<a.length&&B.A.push({f:[d,n],type:e?"Block":"Line",value:a})}function E(a){switch(a){case o.Z:return"Boolean";case o.a:return"Identifier";case o.v:return"Keyword";
case o.ia:return"Null";case o.w:return"Numeric";case o.e:return"Punctuator";case o.L:return"String";default:m(Error("Unknown token type"))}}function g(){var a,b;if(D)return n=D.f[1],r=D.lineNumber,b=D,D=I,b;D=I;N();a=n;b=ia();b.f=[a,n];b.lineNumber=r;b.type!==o.t&&B.m.push({type:E(b.type),value:y.slice(a,n),f:[a,n-1]});return b}function qa(){var a,b,d;N();a=n;b=B.ta();0<B.m.length&&(d=B.m[B.m.length-1],d.f[0]===a&&"Punctuator"===d.type&&("/"===d.value||"/="===d.value)&&B.m.pop());B.m.push({type:"RegularExpression",
value:b.Sa,f:[a,n-1]});return b}function Q(){var a,b;N();a=n;b=L();b.f=[a,n-1];return b}function Z(a){function b(a,b){if(a.hasOwnProperty("range")&&b.hasOwnProperty("range"))return[a.f[0],b.f[1]]}pa(a,function(a){"BinaryExpression"===a.type&&!a.hasOwnProperty("range")&&(a.f=b(a.left,a.right));"LogicalExpression"===a.type&&(a.f=b(a.left,a.right))});return a}function P(a,b){var d,h;d=b||{};y=a;n=0;r=0<y.length?1:0;C=y.length;D=I;B={};"boolean"===typeof d.Pa&&d.Pa&&(B.Ba=N,N=O,B.A=[]);"boolean"===typeof d.f&&
d.f&&(B.za=ca,ca=Q);"boolean"===typeof d.m&&d.m&&(B.xa=k,B.ta=X,k=g,X=qa,B.m=[]);try{for(var c=e.ja,l,j=[];n<C;){if(K().type!==o.t){var q=t;if(u("function")){var W=t,f=I,ka=[],v=t;w("function");W=k();W.type!==o.a&&H(W);f={type:e.a,name:W.value};p("(");if(!i(")"))for(;n<C;){W=k();W.type!==o.a&&H(W);ka.push({type:e.a,name:W.value});if(i(")"))break;p(",")}p(")");v=x();q={type:e.I,id:f,p:ka,body:v}}else q=A();l=q}else l=t;if("undefined"===typeof l)break;j.push(l)}h={type:c,body:j};"undefined"!==typeof B.A&&
(h.A=B.A);"undefined"!==typeof B.m&&(h.m=B.m);"boolean"===typeof d.f&&d.f&&(h=Z(h))}catch(na){m(na)}finally{"function"===typeof B.Ba&&(N=B.Ba),"function"===typeof B.za&&(ca=B.za),"function"===typeof B.xa&&(k=B.xa),"function"===typeof B.ta&&(X=B.ta),B={}}return h}function T(a,b){var d,e;if(b(a)!==R)for(d in a)a.hasOwnProperty(d)&&(e=a[d],"object"===typeof e&&T(e,b))}function pa(a,b){var d,e;for(d in a)a.hasOwnProperty(d)&&(e=a[d],"object"===typeof e&&pa(e,b));b(a)}var o,e,F,y,n,r,C,D,B;o={Z:1,t:2,
a:3,v:4,ia:5,w:6,e:7,L:8};e={D:1,C:2,Y:3,j:4,F:5,k:6,$:7,aa:8,G:9,ca:10,ba:11,da:12,H:13,fa:14,ea:15,I:16,n:17,a:18,ga:19,g:20,ha:21,J:22,o:23,Q:24,R:25,ja:26,K:27,S:28,T:29,ka:30,la:31,ma:32,na:33,M:34,N:35,O:36,oa:37,pa:38};U.Ua=e;F={U:"Unexpected token %0",La:"Unexpected number",Na:"Unexpected string",Ka:"Unexpected identifier",Ma:"Unexpected reserved word",Ja:"Unexpected end of input",Ha:"Illegal newline after throw",Ga:"Invalid regular expression",Oa:"Invalid regular expression: missing /",Ca:"Invalid left-hand side in assignment",
Da:"Invalid left-hand side in for-in",Ea:"Invalid left-hand side expression in postfix operation",Fa:"Invalid left-hand side expression in prefix operation",Ia:"Missing catch or finally after try"};"function"===typeof Object.freeze&&(Object.freeze(o),Object.freeze(e),Object.freeze(F));U.version="0.9.5";U.parse=P;U.Za=function(a,b,d){typeof b==="undefined"&&m(Error("Wrong use of traverse() function"));if(typeof d==="undefined"){d=b;b={}}a=P(a,b);T(a,d);return a}})("undefined"===typeof exports?esprima=
{}:exports);
(function(){var U,V,ea,S,$,f,N,ha,X,ia,k;function K(c){var i;try{i=new ActiveXObject("Msxml2.XMLHTTP")}catch(f){try{i=new ActiveXObject("Microsoft.XMLHTTP")}catch(j){i=R}}!i&&"undefined"!=typeof XMLHttpRequest&&(i=new XMLHttpRequest);i.open("GET",c,R);i.send(I);return i.responseText}function aa(c){var i=[],c=c.replace("\\","/").split("/"),f;for(f in c)".."==c[f]?i.pop():i.push(c[f]);return i.join("/")}function s(){return{d:{},u:{},l:{},depth:-1}}function H(){var c,i,f,j,k,x=arguments[0]||{},J=1,s=
arguments.length,h=R;"boolean"===typeof x&&(h=x,x=arguments[1]||{},J=2);"object"!==typeof x&&"function"!==p(x)&&(x={});s===J&&(x=this,--J);for(;J<s;J++)if((c=arguments[J])!=I)for(i in c)f=x[i],j=c[i],x!==j&&(h&&j&&(w(j)||(k="array"===p(j)))?(k?(k=R,f=f&&"array"===p(f)?f:[]):f=f&&w(f)?f:{},x[i]=H(h,f,j)):j!==t&&(x[i]=j));return x}function p(c){return c==I?""+c:M[ma.call(c)]||"object"}function w(c){if(!c||"object"!==p(c)||c.nodeType||c&&"object"===typeof c&&"setInterval"in c)return R;try{if(c.constructor&&
!fa.call(c,"constructor")&&!fa.call(c.constructor.prototype,"isPrototypeOf"))return R}catch(i){return R}for(var f in c);return f===t||fa.call(c,f)}function i(){da&&L.apply(I,arguments)}function u(c,i){for(var f in i)c[f]=i[f]}function ba(c,i){u(c.d,i.d);u(c.u,i.u);u(c.l,i.l);c.depth=i.depth;return c}function G(c){return c+"$"}function L(c,i,f,j,k,x){switch(arguments.length){case 1:console.log(c);break;case 2:console.log(c,i);break;case 3:console.log(c,i,f);break;case 4:console.log(c,i,f,j);break;
case 5:console.log(c,i,f,j,k);break;default:console.log(arguments)}}function ca(c){for(var c=c.split(/(\\|\/)/),i="",f=0;f<c.length-1;++f)if(c[f].length&&(!("/"==c[f]||"\\"==c[f])||!i.length))i+=c[f]+("/"!=c[f]?"/":"");return("/"==c[0]||"\\"==c[0]?"/":"")+i}var da=R,la="_"+(new Date).getTime(),M={},ma=Object.prototype.toString,fa=Object.prototype.hasOwnProperty;(function(){for(var c="Boolean,Number,String,Function,Array,Date,RegExp,Object".split(","),i=0,f=c.length;i<f;++i)M["[object "+c[i]+"]"]=
c[i].toLowerCase()})();var c=esprima.Ua;U="Define";V="Enum";ea="Undef";S="Include";$="If";f="Endif";N="Elseif";ha="Ifdef";X="__";ia="__FILE__";k="__LINE__";var Y=[],ja={s:0};(function(){function p(j,v,x,J,w,h){function l(a){D.push(C);C=a}function q(){C=D.length?D.pop():w}function ga(){B.push(y);y=z}function A(a){if(C&&v){switch(r.substr(-2,2)){case ";\n":return;case "}\n":a&&(r=r.substr(0,r.length-1)+";\n");return}g(";\n")}}function O(a){return"//"+F+"// "+a}function E(){C&&g("\n")}function g(a){r+=
a;h.s++}function s(a){var b=a.object;return b&&b.type==c.o?s(b):a}function Q(a){for(var b=0;b<a.length;++b)e(a[b]),b!=a.length-1&&g(", ")}function K(a){function b(a){a.type==c.D||a.type==c.j||a.type==c.N||a.type==c.M||a.type==c.J?(g("("),e(a),g(")")):e(a)}if(!J){var d=G(u(a,h)),f=x.d[d];if(f&&!f.q[d+"#"+h.s]){f.q[d+"#"+h.s]=1;e(f);return}var f=a.d,j;if(f.type==c.a&&(d=f.name+"$",f=x.d[d]))d=s(f),d.object&&d.object.name==X&&(da&&(j=u(a,h)),a.W=f.W,a.d=f.d,i(O(j+" ==> "+u(a,h))))}l(R);j=a.object;a.W?
(b(j),g("["),e(a.d),g("]")):(b(j),g("."),e(a.d));q();A()}function P(a){if(y)ga();else{a=a.arguments[0];try{eval(p(a,z,x,R,C,h))||ga()}catch(b){m(b)}}}function T(a){var b=a.callee;if(b.type==c.a){switch(b.name){case f:y=B.length?B.pop():R;return;case N:a.arguments.length&&m(Error("Parametric ElseIf unsupported!"));len=B.length;if(!y||B[len-1]===R)y=!y;return;case $:P(a);return;case ha:if(y)ga();else{a=a.arguments[0];try{x.d[a.name+"$"]||ga()}catch(d){m(d)}}return}if(y)return;switch(b.name){case S:J||
(a=a.arguments,a.length&&(a=a[0].value,Y.push(ca(a)),a=a.replace(/^.*[\\\/]/,""),""==a&&(a=Preprocessor.defaultInclude),a=aa(Y.join("")+a),(b=x.l[a])?b.Wa?console.warn("<include: "+a+"> already been used."):b.Ta?L("<include: "+a+"> skipped. "):(b.Wa=z,n=a,e(b),n=""):console.warn("<include: "+a+"> not found."),Y.pop()));return;case ea:J||(a=a.arguments,b=u(a[0],h),a[0].type==c.k?(b=Preprocessor.i(a[0].callee,R),b+="+"+a[0].arguments.length,delete x.u[b]):delete x.d[b+"$"]);return;case U:case V:return}}if(!y){if(!J){var j=
u(b,h)+"+"+a.arguments.length,o=x.u[j];if(o&&!o.q[j+"#"+h.s]){var k=o.V,r=a.arguments,v,w,E;if(k.length==r.length){++x.depth;w={};E={};o.q[j+"#"+h.s]=1;for(var b=x.d,s=0;s<k.length;++s){v=k[s].Va;var D=k[s].name+"$";if(b[D]){if(0<x.depth){var F=G(u(r[s],h));r[s]=H(z,{},b[F])}else F=O("::erase arg <"+k[s].name+"> ("+u(b[D],h)+" ==> "+u(r[s],h)+") in call: "+j),console.warn(F);w[D]=b[D]}else w[D]=I;v&&(r[s]={type:c.g,value:p(r[s],R,x,R,C,h)});E[D]=r[s];E[D].q={}}for(s in E)b[s]=E[s];j=p(o.rel.body.body,
z,x,R,C,h);for(s in w)w[s]!=I?b[s]=w[s]:delete b[s];i(O(u(a,h)+" ==> "+j));--x.depth;g(j);return}}}a.callee.type!=c.n?(l(R),e(a.callee),g("("),Q(a.arguments),g(")"),q()):(g("("),e(a.callee),g(")"),g("("),l(R),Q(a.arguments),q(),g(")"));A()}}function M(a,b){b||R||g("function");g("(");l(R);Q(a.p);q();g(")");l(z);e(a.body);q()}function o(a){function b(a){a.type==c.S?(g("("),e(a),g(")")):e(a)}l(R);g("(");e(a.test);g("? ");b(a.r);g(" : ");b(a.z);g(")");q();A()}function e(a){if(a)if(a instanceof Array)for(var b=
0;b<a.length;++b)e(a[b]);else if(y)a.type==c.k?T(a):a.type==c.H&&(e(a.b),A(1));else switch(a.type){case c.D:l(R);e(a.left);g(" "+a.c+" ");e(a.right);q();A();break;case c.C:g("[");l(R);Q(a.elements);q();g("]");A();break;case c.Y:g(" {\n");l(z);e(a.body);g("\n}\n");q();break;case c.j:l(R);var b=a.left.type,d=a.right.type;b==c.a||b==c.g?e(a.left):(g("("),e(a.left),g(")"));g(" "+a.c+" ");d==c.a||d==c.g?e(a.right):(g("("),e(a.right),g(")"));q();A();break;case c.F:g("break ");l(R);e(a.label);q();A();break;
case c.k:T(a);break;case c.$:g("catch");g("(");l(R);e(a.ya);q();g(")");l(z);e(a.body);q();break;case c.aa:o(a);break;case c.G:g("continue ");l(R);e(a.label);q();A();break;case c.ca:g("do");l(z);e(a.body);q();g("while");g("(");l(R);e(a.test);q();g(")");E();break;case c.ba:g("debugger");A();break;case c.da:A();break;case c.H:e(a.b);A(1);break;case c.fa:g("for ");l(R);g("(");e(a.B);g("; ");e(a.test);g("; ");e(a.update);g(")");q();l(z);e(a.body);q();E();break;case c.ea:g("for ");l(R);g("(");e(a.left);
g(" in ");e(a.right);g(")");q();l(z);e(a.body);q();E();break;case c.I:g("function ");l(R);e(a.id);q();g("(");l(R);Q(a.p);q();g(")");l(z);e(a.body);q();E();break;case c.n:M(a);break;case c.a:a:{b=a.name;if(!J){var d=b+"$",f=x.d[d];if(f&&!f.q[d+"#"+h.s]){f.q[d+"#"+h.s]=1;if(f.type!=c.o){i(O(u(a,h)+" ==> "+u(f,h)));f.type!=c.a&&f.type!=c.I&&f.type!=c.n&&f.type!=c.R&&f.type!=c.C&&f.type!=c.k&&f.type!=c.g?(g("("),e(f),g(")")):e(f);break a}if(s(f).object.name!=X){e(f);break a}}}b==ia?g('"'+n+'"'):b==k?
g('""'):g(b);A()}break;case c.ga:l(R);g("if (");e(a.test);g(")");q();l(z);e(a.r);a.z&&(g("else "),e(a.z));q();E();break;case c.g:"string"==typeof a.value?(a=(""+a.value).replace(/\\"/g,'"').replace(/"/g,'\\"').replace(/\n/g,""),g('"'+a+'"')):g(a.value);A();break;case c.ha:b=a.label;l(R);e(b);g(":\n");e(a.body);q();break;case c.J:b=a.left.type;d=a.right.type;l(R);b==c.a||b==c.g?e(a.left):(g("("),e(a.left),g(")"));g(" "+a.c+" ");d==c.a||d==c.g?e(a.right):(g("("),e(a.right),g(")"));q();A();break;case c.o:K(a);
break;case c.Q:g("new ");l(R);b=a.callee;J?(b.type==c.a||b.type==c.o?e(b):(g("("),e(b),g(")")),g("("),Q(a.arguments),g(")")):(d=p(b,R,x,R,R,h),b.type!=c.a&&b.type!=c.o&&(d="("+d+")"),a=H(z,{},a),a.callee={type:c.a,name:d},a.type=c.k,e(a));q();A();break;case c.R:b=a.Aa;g(" {");l(R);for(d=0;d<b.length;++d)(f=b[d].P)?"get"==f||"set"==f?(b[d].value.type!=c.n&&m(Error("unsupported getter")),g(f+" "),e(b[d].key),g(" "),M(b[d].value,z)):(L(a),m(Error("unsupported <kind: "+f+"> of object member"))):(e(b[d].key),
g(": "),e(b[d].value)),d!=b.length-1&&g(", ");q();g("}");A();break;case c.ja:e(a.body);break;case c.K:g("return ");l(R);e(a.h);q();A();break;case c.S:l(R);Q(a.sa);q();break;case c.T:g("switch");g("(");l(R);e(a.ra);q();g(")");g(" {");e(a.va);g("}");E();break;case c.ka:l(R);a.test==I?g("\ndefault:\n"):(g("\ncase "),e(a.test),g(":\n"));q();l(z);e(a.r);q();A();break;case c.la:g("this");break;case c.ma:g("throw ");e(a.h);A();break;case c.na:g("try");l(z);e(a.ua);e(a.Ra);a.wa&&(g("finally"),e(a.wa));q();
A();break;case c.M:g(a.c);1<a.c.length&&g(" ");b=a.h.type;l(R);b==c.a||b==c.g?e(a.h):(g("("),e(a.h),g(")"));q();A();break;case c.N:a.prefix&&g(a.c);l(R);e(a.h);q();a.prefix||g(a.c);A();break;case c.O:a=a.X;g("var ");l(R);for(b=0;b<a.length;++b)d=a[b],e(d.id),d.B&&(g("="),e(d.B)),b!=a.length-1&&g(", ");q();A(z);break;case c.oa:g("while ");g("(");l(R);e(a.test);q();g(")");l(z);e(a.body);q();break;case c.pa:g("with ");g("(");l(R);e(a.object);q();g(")");l(z);e(a.body);q();break;default:console.log("TODO: unsupported code structure"),
L(a)}}var v=v===t?z:v,J=J===t?z:J,x=x||I,F=da?Math.floor(1E6*Math.random()):"",y=R,w=w===t?z:w,n="",r="",C=w,D=[],B=[];e(j);return r}function u(c,f){return p(c,R,I,z,z,f)}var w=s();Preprocessor.i=function(c,f,i,k,u){k===z&&(w=s());i&&(w=ba(w,i));ja.s++;return p(c,f,w,i?R:z,u,ja)}})();(function(){function k(){G.push(u);u=z}function p(h){var h=h.arguments,f=Preprocessor.i(h[0],R);if(h[0].type==c.k){var f=Preprocessor.i(h[0].callee,R),i=h[0].arguments.length,j=f.replace(/\./g,"_")+"_"+i+la,f=f+("+"+
i);if(x){for(var k=s(),u=0;u<i;++u){var w=h[0].arguments[u],g=w.name;"$$"==g.substr(0,2)&&(g=g.substr(2),w.Va=z);w.name=j+"_"+g;w.q={};k.d[g+"$"]=w}i=Preprocessor.i(h[1].body,z,k,z,z);try{h[1].body.body=esprima.parse(i).body[0].body}catch(G){L("error after function modification, param name replacing..."),L(Preprocessor.i(h[1].body,z,I,z,z)),L(i),L(k),m(G)}}v.u[f]={V:h[0].arguments,rel:h[1],q:{}}}else f+="$",v.d[f]=h[1],v.d[f].q={}}function w(c){if(u)k();else{c=c.arguments[0];try{eval(Preprocessor.i(c,
z,v,R))||k()}catch(f){L("cannot eval If() statament with ignore: "+u),L(v),L("value:"),L(Preprocessor.i(c,z,v,R)),m(f)}}}function j(h){if(h)if(h instanceof Array)for(var l=0;l<h.length;++l)j(h[l]);else switch(h.type){case c.D:j(h.left);j(h.right);break;case c.C:j(h.elements);break;case c.Y:j(h.body);break;case c.j:j(h.left);j(h.right);break;case c.F:break;case c.k:a:{var q=h.callee;if(q&&q.type==c.a){if(q.name==N){if(h.arguments.length&&m(Error("Parametric ElseIf unsupported!")),len=G.length,!u||
G[len-1]===R)u=!u}else q.name==f&&(u=G.length?G.pop():R);if(q.name==$)w(h);else if(q.name==ha)if(u)k();else{var s=h.arguments[0];try{v.d[s.name+"$"]||k()}catch(A){m(A)}}if(u)break a;if(q.name==U)p(h);else if(q.name!=ea)if(q.name==V){var O=h.arguments;if(!(2>O.length)){var E=O[0];if(E.type==c.C){var g=0,q=R,M,s={type:c.k,callee:{type:c.a,name:U},arguments:[I,{type:c.g,value:0}]},Q=I,Z;2<O.length&&(Q=Preprocessor.i(O[2],R));for(var E=E.elements,P=0,T;P<E.length;++P){O=R;T=H(z,{},s);E[P].type==c.D?(O=
z,Z=E[P].left,E[P].right.type===c.g&&"string"===typeof E[P].right.value?(l=E[P].right.value,(M=l.match(/^(.*?\w)(\d+)$/i))?(l=M[1],g=Number(M[2])):g=0,q=l):(q=I,g=Number(Preprocessor.i(E[P].right,R,v)))):Z=E[P];if(Q)try{Z=esprima.parse(Q+"."+Preprocessor.i(Z,R)).body}catch(X){m(X)}q===I?(T.arguments[0]=Z,T.arguments[1].value=g):(M&&(l+=g),O||(l=q+g),T.arguments[0]=Z,T.arguments[1].value=l);g++;i("//"+("Enum: "+Preprocessor.i(Z,R)+" : "+l));p(T)}}}}else if(q.name==S)b:if(l=h.arguments,l.length){l=
l[0].value;Y.push(ca(l));l=l.replace(/^.*[\\\/]/,"");""==l&&(l=Preprocessor.defaultInclude);l=aa(Y.join("")+l);if(!v.l[l]){try{E=K(l)}catch(o){o instanceof SyntaxError||m(o)}if(!E.length)break b;try{g=esprima.parse(E)}catch(e){L("ERROR:: syntax error in: "+l),m(e)}v=Preprocessor.qa(g,v,x);v.l[l]=g.body}Y.pop()}}else j(h.callee);j(h.arguments)}break;case c.$:j(h.ya);j(h.Qa);j(h.body);break;case c.aa:j(h.test);j(h.r);j(h.z);break;case c.G:break;case c.ca:j(h.body);j(h.test);break;case c.ba:break;case c.da:break;
case c.H:j(h.b);break;case c.fa:j(h.B);j(h.test);j(h.update);j(h.body);break;case c.ea:j(h.left);j(h.right);j(h.body);break;case c.I:j(h.p);j(h.body);break;case c.n:j(h.p);j(h.body);break;case c.a:break;case c.ga:j(h.test);j(h.r);j(h.z);break;case c.g:break;case c.ha:j(h.body);break;case c.J:j(h.left);j(h.right);break;case c.o:j(h.object);break;case c.Q:j(h.arguments);break;case c.R:h=h.Aa;for(l=0;l<h.length;++l)j(h[l].key),j(h[l].value);break;case c.ja:j(h.body);break;case c.K:j(h.h);break;case c.S:j(h.sa);
break;case c.T:j(h.ra);j(h.va);break;case c.ka:j(h.test);j(h.r);break;case c.la:break;case c.ma:j(h.h);break;case c.na:j(h.ua);break;case c.M:j(h.h);break;case c.N:j(h.h);break;case c.O:h=h.X;for(l=0;l<h;++l)j(h[l].id),j(h[l].B);break;case c.oa:j(h.test);j(h.body);break;case c.pa:j(h.object);j(h.body);break;default:console.log("unknown syntax structure founded:"),console.log(h)}}var v,x,u,G=[];Preprocessor.qa=function(c,f,k){u=R;G=[];x=k===t?z:k;i("SubstArg: "+x);k=s();v=f?ba(k,f):k;j(c);return v};
Preprocessor.code=function(c,f){da=Preprocessor.debug;Y=[];try{var j=esprima.parse(c)}catch(k){m(k)}var p=Preprocessor.qa(j);Preprocessor.next=function(c){if("object"==typeof c&&c.l)for(var f in c.l)c.l[f]===R&&(p.l[f].Ta=z);i("=====> reflect starting...");i(p);return Preprocessor.i(j,z,p,z)};if("object"==typeof f){var s={};if(f.l){var u=s.l={},g;for(g in p.l)u[g]=z}return s}return Preprocessor.next()};Preprocessor.file=function(c){return Preprocessor.code(K(c))};Preprocessor.watch=function(){var c=
document.getElementsByTagName("script"),f="",i;for(i in c){var j=c[i];j.type==Preprocessor.scriptType&&(j.src&&(f+=K(j.src)),f+=j.innerHTML)}c=document.getElementsByTagName("head")[0];script=document.createElement("script");script.type="text/javascript";script.innerHTML=Preprocessor.code(f);script.id="akra-js-"+(new Date).getTime();c.appendChild(script)};Preprocessor.extractMacro=function(c){var f;try{f=esprima.parse(c)}catch(i){L("esprima parse error: "),m(i)}Preprocessor.qa(f,I,R);var c="",j;for(j in v.d)c+=
("Define("+j.substr(0,j.length-1)+","+Preprocessor.i(v.d[j],z,0,0,R)+")").replace(/(\r\n|\n|\r)/gm,"")+"\n";for(j in v.u){f=v.u[j];for(var k="",k=k+("Define("+j.substr(0,j.lastIndexOf("+"))+"("),p=0;p<f.V.length;++p)k+=Preprocessor.i(f.V[p],R)+(p!=f.V.length-1?",":"");k+="),function()"+Preprocessor.i(f.rel.body,z,0,0,R)+")";c+=k.replace(/(\r\n|\n|\r)/gm,"")+"\n"}return c};Preprocessor.extractFileMacro=function(c){return this.Ya(K(c))};Preprocessor.watch()})()})("undefined"===typeof exports?Preprocessor=
{defaultInclude:"Include.js",debug:R,scriptType:"text/akra-js"}:exports);