/*
 Akra Javascript Preprocessor:
 Copyright (C) 2011-2012 Akra Engine <akra@odserve.org>

 Esprima:
 Copyright (C) 2011 Ariya Hidayat <ariya.hidayat@gmail.com>

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright
 notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in the
 documentation and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 PREPROCESSOR VER.: 1.2.0
 */


function p(N){throw N;}var s=void 0,x=!0,M=null,U=!1;
(function(N){function V(a){return 0<="0123456789".indexOf(a)}function ha(a){return" "===a||"\t"===a||"\x0B"===a||"\u000c"===a||"\u00a0"===a||"\ufeff"===a}function W(a){return"\n"===a||"\r"===a||"\u2028"===a||"\u2029"===a}function da(a){return"$"===a||"_"===a||"a"<=a&&"z">=a||"A"<=a&&"Z">=a}function e(){var a="\x00",c=l;c<B&&(a=C[c],l+=1);return a}function R(){var a,c,b;for(b=c=U;l<B;)if(a=C[l],b)e(),W(a)&&(b=U,u+=1);else if(c)e(),"*"===a?(a=C[l],"/"===a&&(e(),c=U)):W(a)&&(u+=1);else if("/"===a)if(a=
    C[l+1],"/"===a)e(),e(),b=x;else if("*"===a)e(),e(),c=x;else break;else if(ha(a))e();else if(W(a))e(),u+=1;else break}function ja(){var a=C[l],c,b,g;if(";"===a||"{"===a||"}"===a)return e(),{type:q.e,value:a};if(","===a||"("===a||")"===a)return e(),{type:q.e,value:a};c=C[l+1];if("."===a&&!V(c))return{type:q.e,value:e()};b=C[l+2];g=C[l+3];if(">"===a&&">"===c&&">"===b&&"="===g)return e(),e(),e(),e(),{type:q.e,value:">>>="};if("="===a&&"="===c&&"="===b)return e(),e(),e(),{type:q.e,value:"==="};if("!"===
    a&&"="===c&&"="===b)return e(),e(),e(),{type:q.e,value:"!=="};if(">"===a&&">"===c&&">"===b)return e(),e(),e(),{type:q.e,value:">>>"};if("<"===a&&"<"===c&&"="===b)return e(),e(),e(),{type:q.e,value:"<<="};if(">"===a&&">"===c&&"="===b)return e(),e(),e(),{type:q.e,value:">>="};if("="===c&&0<="<>=!+-*%&|^/".indexOf(a))return e(),e(),{type:q.e,value:a+c};if(a===c&&0<="+-<>&|".indexOf(a)&&0<="+-<>&|".indexOf(c))return e(),e(),{type:q.e,value:a+c};if(0<="[]<>+-*%&|^!~?:=/".indexOf(a))return{type:q.e,value:e()}}
    function ea(){var a="",c,b,g,d;b=U;n=M;R();c=C[l];if("/"===c){for(a=e();l<B;)if(c=e(),a+=c,b)"]"===c&&(b=U);else{"\\"===c&&(a+=e());if("/"===c)break;"["===c&&(b=x);W(c)&&E(G.Pa,u)}b=a.substr(1,a.length-2);for(g="";l<B;){c=C[l];if(!(da(c)||"0"<=c&&"9">=c))break;g+=c;a+=e()}try{d=RegExp(b,g)}catch(h){E(G.Ha,u)}return{Ta:a,value:d}}}function ca(){var a;if(l>=B)return{type:q.t};a=ja();if("undefined"!==typeof a)return a;a=C[l];if("'"===a||'"'===a){var c;var b="";a=C[l];if(!("'"!==a&&'"'!==a)){for(e();l<
        B;)if(c=e(),c===a){a="";break}else"\\"===c?(c=e(),W(c)||(b+="\\",b+=c)):b+=c;""!==a&&E(G.T,u,"ILLEGAL");c={type:q.K,value:b}}return c}if("."===a||V(a)){a:if(c=C[l],V(c)||"."===c){b="";if("."!==c){b=e();c=C[l];if("x"===c||"X"===c){for(b+=e();l<B;){c=C[l];if(!(0<="0123456789abcdefABCDEF".indexOf(c)))break;b+=e()}b={type:q.v,value:parseInt(b,16)};break a}for(;l<B;){c=C[l];if(!V(c))break;b+=e()}}if("."===c)for(b+=e();l<B;){c=C[l];if(!V(c))break;b+=e()}if("e"===c||"E"===c)if(b+=e(),c=C[l],"+"===c||"-"===
        c||V(c))for(b+=e();l<B;){c=C[l];if(!V(c))break;b+=e()}else E(G.T,u,"ILLEGAL");b={type:q.v,value:parseFloat(b)}}return b}b=C[l];if(da(b)){for(c=e();l<B;){b=C[l];if(!(da(b)||"0"<=b&&"9">=b))break;c+=e()}if(1===c.length)c={type:q.a,value:c};else{b:{switch(c){case "break":case "case":case "catch":case "continue":case "debugger":case "default":case "delete":case "do":case "else":case "finally":case "for":case "function":case "if":case "in":case "instanceof":case "new":case "return":case "switch":case "this":case "throw":case "try":case "typeof":case "var":case "void":case "while":case "with":case "class":case "const":case "enum":case "export":case "extends":case "import":case "super":case "implements":case "interface":case "let":case "package":case "private":case "protected":case "public":case "static":case "yield":b=
        x;break b}b=U}c=b?{type:q.u,value:c}:"null"===c?{type:q.ha}:"true"===c||"false"===c?{type:q.Y,value:c}:{type:q.a,value:c}}a=c}else a=s;if("undefined"!==typeof a)return a;E(G.T,u,"ILLEGAL")}function o(){var a,c;if(n)return l=n.f[1],u=n.lineNumber,c=n,n=M,c;n=M;R();a=l;c=ca();c.f=[a,l];c.lineNumber=u;return c}function T(){var a,c,b;if(n!==M)return n;a=l;c=u;b=o();l=a;u=c;return n=b}function Z(){var a,c,b;a=l;c=u;R();b=u!==c;l=a;u=c;return b}function E(a,c){var b=Array.prototype.slice.call(arguments,
        2);p(Error("Line "+c+": "+a.replace(/%(\d)/g,function(a,c){return b[c]||""})))}function O(a){a.type===q.t&&E(G.Ka,u);a.type===q.v&&E(G.Ma,u);a.type===q.K&&E(G.Oa,u);a.type===q.a&&E(G.La,u);a.type===q.u&&E(G.Na,u);a=a.value;10<a.length&&(a=a.substr(0,10)+"...");E(G.T,u,a)}function j(a){var c=o();(c.type!==q.e||c.value!==a)&&O(c)}function H(a){var c=o();(c.type!==q.u||c.value!==a)&&O(c)}function i(a){var c=T();return c.type===q.e&&c.value===a}function y(a){var c=T();return c.type===q.u&&c.value===a}
    function X(a){return a.type===k.a||a.type===k.q||a.type===k.l||a.type===k.P}function F(){var a;";"===C[l]?o():(a=u,R(),u===a&&(i(";")?o():(a=T(),a.type!==q.t&&!i("}")&&O(a))))}function ka(){var a;if(i("[")){a=[];for(j("[");l<B;){if(i("]")){o();break}if(i(","))o(),a.push(s);else{a.push(J());if(i("]")){o();break}j(",")}}return{type:k.B,elements:a}}if(i("{")){var c=[],b;for(j("{");l<B;){a=o();if(a.type===q.e&&"}"===a.value)break;b={};switch(a.type){case q.a:b.key={type:k.a,name:a.value};if("get"===a.value&&
        !i(":")){a=o();a.type!==q.a&&O(a);j("(");j(")");b={key:{type:k.a,name:a.value},value:{type:k.p,id:M,r:[],body:fa()},O:"get"};break}if("set"===a.value&&!i(":")){a=o();a.type!==q.a&&O(a);b.key={type:k.a,name:a.value};j("(");a=o();a.type!==q.a&&O(a);j(")");b.value={type:k.p,id:M,r:[{type:k.a,name:a.value}],body:fa()};b.O="set";break}j(":");b.value=J();break;case q.K:case q.v:b.key={type:k.g,value:a.value};j(":");b.value=J();break;default:O(a)}c.push(b);a=T();if(a.type===q.e&&"}"===a.value){o();break}j(",")}return{type:k.Q,
        Ba:c}}if(i("("))return o(),a=r(),j(")"),a.c;if(y("function")){a=M;c=[];H("function");i("(")||(b=o(),b.type!==q.a&&O(b),a={type:k.a,name:b.value});j("(");if(!i(")"))for(;l<B;){b=o();b.type!==q.a&&O(b);c.push({type:k.a,name:b.value});if(i(")"))break;j(",")}j(")");b=fa();return{type:k.p,id:a,r:c,body:b}}if(y("this"))return o(),{type:k.ka};if(i("/")||i("/="))return{type:k.g,value:ea().value};a=o();return a.type===q.a?{type:k.a,name:a.value}:a.type===q.Y?{type:k.g,value:"true"===a.value}:a.type===q.ha?
    {type:k.g,value:M}:a.type===q.v?{type:k.g,value:a.value}:a.type===q.K?{type:k.g,value:a.value}:O(a)}function ga(){return ka()}function P(){var a=[];j("(");if(!i(")"))for(;l<B;){a.push(J());if(i(")"))break;j(",")}j(")");return a}function la(){var a,c,b;if(a=y("new"))o(),c=la();else{var g;for(c=ga();l<B;)if(i("."))o(),g=o(),g.type!==q.a&&O(g),g={type:k.a,name:g.value},c={type:k.q,V:U,object:c,b:g};else if(i("["))o(),g=r(),g.type===k.G&&(g=g.c),c={type:k.q,V:x,object:c,b:g},j("]");else if(i("("))c={type:k.l,
        callee:c,arguments:P()};else break}i("(")&&(b=P());return a?("undefined"===typeof b&&(b=[]),c.type===k.l&&(b=c.arguments,c=c.callee),{type:k.P,callee:c,arguments:b}):"undefined"!==typeof b?{type:k.l,callee:c,arguments:b}:c}function aa(){var a,c;if(i("++")||i("--"))return a=o().value,c=aa(),X(c)||E(G.Ga,u),{type:k.M,d:a,h:c,prefix:x};if(i("+")||i("-")||i("~")||i("!"))a={type:k.L,d:o().value,h:aa()};else if(y("delete")||y("void")||y("typeof"))a={type:k.L,d:o().value,h:aa()};else if(a=la(),(i("++")||
        i("--"))&&!Z())X(a)||E(G.Fa,u),a={type:k.M,d:o().value,h:a,prefix:U};return a}function oa(){for(var a=aa();i("*")||i("/")||i("%");)a={type:k.k,d:o().value,left:a,right:aa()};return a}function ma(){for(var a=oa();i("+")||i("-");)a={type:k.k,d:o().value,left:a,right:oa()};return a}function $(){var a;for(a=ma();i("<<")||i(">>")||i(">>>");)a={type:k.k,d:o().value,left:a,right:ma()};i("<")||i(">")||i("<=")||i(">=")?a={type:k.k,d:o().value,left:a,right:$()}:y("in")?(o(),a={type:k.k,d:"in",left:a,right:$()}):
        y("instanceof")&&(o(),a={type:k.k,d:"instanceof",left:a,right:$()});return a}function Y(){for(var a=$();i("==")||i("!=")||i("===")||i("!==");)a={type:k.k,d:o().value,left:a,right:$()};return a}function d(){for(var a=Y();i("&");)o(),a={type:k.k,d:"&",left:a,right:Y()};return a}function ba(){for(var a=d();i("|");)o(),a={type:k.k,d:"|",left:a,right:d()};return a}function na(){for(var a=ba();i("^");)o(),a={type:k.k,d:"^",left:a,right:ba()};return a}function ia(){for(var a=na();i("&&");)o(),a={type:k.I,
        d:"&&",left:a,right:na()};return a}function J(){var a;for(a=ia();i("||");)o(),a={type:k.I,d:"||",left:a,right:ia()};i("?")&&(o(),a={type:k.$,test:a},a.s=J(),j(":"),a.w=J());var c=T(),b=c.value;if(c.type!==q.e?0:"="===b||"*="===b||"/="===b||"%="===b||"+="===b||"-="===b||"<<="===b||">>="===b||">>>="===b||"&="===b||"^="===b||"|="===b)X(a)||E(G.Da,u),a={type:k.C,d:o().value,left:a,right:J()};return a}function r(){var a=J();if(i(","))for(a={type:k.R,ra:[a]};l<B&&i(",");)o(),a.ra.push(J());return{type:k.G,
        c:a}}function fa(){j("{");for(var a=[],c;l<B&&!i("}");){c=f();if("undefined"===typeof c)break;a.push(c)}j("}");return{type:k.X,body:a}}function m(){var a,c;a=o();a.type!==q.a&&O(a);a={type:k.a,name:a.value};c=M;i("=")&&(o(),c=J());return{id:a,A:c}}function D(){for(var a=[];l<B;){a.push(m());if(!i(","))break;o()}return a}function ta(){var a,c=M;H("continue");if(";"===C[l])return o(),{type:k.F,label:M};if(Z())return{type:k.F,label:M};a=T();a.type===q.a&&(o(),c={type:k.a,name:a.value});F();return{type:k.F,
        label:c}}function L(){var a,c=M;H("break");if(";"===C[l])return o(),{type:k.D,label:M};if(Z())return{type:k.D,label:M};a=T();a.type===q.a&&(o(),c={type:k.a,name:a.value});F();return{type:k.D,label:c}}function t(){var a,c=M;H("return");if(" "===C[l]&&da(C[l+1]))return c=r().c,F(),{type:k.J,h:c};if(Z())return{type:k.J,h:M};i(";")||(a=T(),!i("}")&&a.type!==q.t&&(c=r().c));F();return{type:k.J,h:c}}function g(){for(var a=[],c;l<B&&!i("}")&&!y("default")&&!y("case");){c=f();if("undefined"===typeof c)break;
        a.push(c)}return a}function f(){var a=T(),c;if(a.type!==q.t){if(a.type===q.e)switch(a.value){case ";":return j(";"),{type:k.ca};case "{":return fa();case "(":return c=r(),F(),c}if(a.type===q.u)switch(a.value){case "break":return L();case "continue":return ta();case "debugger":return H("debugger"),F(),{type:k.aa};case "do":var b;H("do");c=f();H("while");j("(");b=r().c;j(")");F();return{type:k.ba,body:c,test:b};case "for":var d,h,n;d=h=a=M;H("for");j("(");if(i(";"))o();else if(y("var")||y("let")?(d=
        o().value,d={type:k.N,W:D(),O:d},y("in")&&(o(),c=d,b=r().c,d=M)):d=r().c,"undefined"===typeof c)d.hasOwnProperty("operator")&&"in"===d.d?(c=d.left,b=d.right,d=M,X(c)||E(G.Ea,u)):j(";");if("undefined"===typeof c&&(i(";")||(h=r().c),j(";"),!i(")")))a=r().c;j(")");n=f();return"undefined"===typeof c?{type:k.ea,A:d,test:h,update:a,body:n}:{type:k.da,left:c,right:b,body:n,Ya:U};case "if":return H("if"),j("("),c=r().c,j(")"),b=f(),y("else")?(o(),h=f()):h=M,{type:k.fa,test:c,s:b,w:h};case "let":return H("let"),
        c=D(),F(),{type:k.N,W:c,O:"let"};case "return":return t();case "switch":H("switch");j("(");c=r().c;j(")");j("{");if(i("}"))o(),c={type:k.S,qa:c};else{for(b=[];l<B&&!i("}");)y("default")?(o(),h=M):(H("case"),h=r().c),j(":"),b.push({type:k.ja,test:h,s:g()});j("}");c={type:k.S,qa:c,wa:b}}return c;case "throw":return H("throw"),Z()&&E(G.Ia,u),c=r().c,F(),{type:k.la,h:c};case "try":return b=[],a=M,H("try"),c=fa(),y("catch")&&(o(),j("("),i(")")||(h=r().c),j(")"),b.push({type:k.Z,za:h,Ra:M,body:fa()})),
        y("finally")&&(o(),a=fa()),0===b.length&&!a&&E(G.Ja,u),{type:k.ma,va:c,Sa:b,xa:a};case "var":return H("var"),c=D(),F(),{type:k.N,W:c,O:"var"};case "while":return H("while"),j("("),c=r().c,j(")"),b=f(),{type:k.na,test:c,body:b};case "with":return H("with"),j("("),c=r().c,j(")"),b=f(),{type:k.oa,object:c,body:b}}c=r();if(c.c.type===k.p&&c.c.id!==M)return{type:k.H,id:c.c.id,r:c.c.r,body:c.c.body};if(c.c.type===k.a&&i(":"))return o(),{type:k.ga,label:c.c,body:f()};F();return c}}function I(){var a,c,b,
        g,d;a="";for(d=g=U;l<B;)if(c=C[l],d)c=e(),W(c)?(d=U,u+=1,A.z.push({f:[b,l-1],type:"Line",value:a}),a=""):a+=c;else if(g)c=e(),a+=c,"*"===c?(c=C[l],"/"===c&&(a=a.substr(0,a.length-1),g=U,e(),A.z.push({f:[b,l-1],type:"Block",value:a}),a="")):W(c)&&(u+=1);else if("/"===c)if(c=C[l+1],"/"===c)b=l,e(),e(),d=x;else if("*"===c)b=l,e(),e(),g=x;else break;else if(ha(c))e();else if(W(c))e(),u+=1;else break;0<a.length&&A.z.push({f:[b,l],type:g?"Block":"Line",value:a})}function v(a){switch(a){case q.Y:return"Boolean";
        case q.a:return"Identifier";case q.u:return"Keyword";case q.ha:return"Null";case q.v:return"Numeric";case q.e:return"Punctuator";case q.K:return"String";default:p(Error("Unknown token type"))}}function w(){var a,c;if(n)return l=n.f[1],u=n.lineNumber,c=n,n=M,c;n=M;R();a=l;c=ca();c.f=[a,l];c.lineNumber=u;c.type!==q.t&&A.o.push({type:v(c.type),value:C.slice(a,l),f:[a,l-1]});return c}function S(){var a,c,b;R();a=l;c=A.sa();0<A.o.length&&(b=A.o[A.o.length-1],b.f[0]===a&&"Punctuator"===b.type&&("/"===b.value||
        "/="===b.value)&&A.o.pop());A.o.push({type:"RegularExpression",value:c.Ta,f:[a,l-1]});return c}function z(){var a,c;R();a=l;c=ka();c.f=[a,l-1];return c}function Q(a){function c(a,c){if(a.hasOwnProperty("range")&&c.hasOwnProperty("range"))return[a.f[0],c.f[1]]}K(a,function(a){"BinaryExpression"===a.type&&!a.hasOwnProperty("range")&&(a.f=c(a.left,a.right));"LogicalExpression"===a.type&&(a.f=c(a.left,a.right))});return a}function qa(a,c){var b,g;b=c||{};C=a;l=0;u=0<C.length?1:0;B=C.length;n=M;A={};"boolean"===
        typeof b.Qa&&b.Qa&&(A.Ca=R,R=I,A.z=[]);"boolean"===typeof b.f&&b.f&&(A.Aa=ga,ga=z);"boolean"===typeof b.o&&b.o&&(A.ya=o,A.sa=ea,o=w,ea=S,A.o=[]);try{for(var d=k.ia,h,ra=[];l<B;){if(T().type!==q.t){var pa=s;if(y("function")){var J=s,sa=M,r=[],m=s;H("function");J=o();J.type!==q.a&&O(J);sa={type:k.a,name:J.value};j("(");if(!i(")"))for(;l<B;){J=o();J.type!==q.a&&O(J);r.push({type:k.a,name:J.value});if(i(")"))break;j(",")}j(")");m=fa();pa={type:k.H,id:sa,r:r,body:m}}else pa=f();h=pa}else h=s;if("undefined"===
        typeof h)break;ra.push(h)}g={type:d,body:ra};"undefined"!==typeof A.z&&(g.z=A.z);"undefined"!==typeof A.o&&(g.o=A.o);"boolean"===typeof b.f&&b.f&&(g=Q(g))}catch(e){p(e)}finally{"function"===typeof A.Ca&&(R=A.Ca),"function"===typeof A.Aa&&(ga=A.Aa),"function"===typeof A.ya&&(o=A.ya),"function"===typeof A.sa&&(ea=A.sa),A={}}return g}function h(a,c){var b,g;if(c(a)!==U)for(b in a)a.hasOwnProperty(b)&&(g=a[b],"object"===typeof g&&h(g,c))}function K(a,c){var g,d;for(g in a)a.hasOwnProperty(g)&&(d=a[g],
        "object"===typeof d&&K(d,c));c(a)}var q,k,G,C,l,u,B,n,A;q={Y:1,t:2,a:3,u:4,ha:5,v:6,e:7,K:8};k={C:1,B:2,X:3,k:4,D:5,l:6,Z:7,$:8,F:9,ba:10,aa:11,ca:12,G:13,ea:14,da:15,H:16,p:17,a:18,fa:19,g:20,ga:21,I:22,q:23,P:24,Q:25,ia:26,J:27,R:28,S:29,ja:30,ka:31,la:32,ma:33,L:34,M:35,N:36,na:37,oa:38};N.Va=k;G={T:"Unexpected token %0",Ma:"Unexpected number",Oa:"Unexpected string",La:"Unexpected identifier",Na:"Unexpected reserved word",Ka:"Unexpected end of input",Ia:"Illegal newline after throw",Ha:"Invalid regular expression",
        Pa:"Invalid regular expression: missing /",Da:"Invalid left-hand side in assignment",Ea:"Invalid left-hand side in for-in",Fa:"Invalid left-hand side expression in postfix operation",Ga:"Invalid left-hand side expression in prefix operation",Ja:"Missing catch or finally after try"};"function"===typeof Object.freeze&&(Object.freeze(q),Object.freeze(k),Object.freeze(G));N.version="0.9.5";N.parse=qa;N.$a=function(a,c,g){typeof c==="undefined"&&p(Error("Wrong use of traverse() function"));if(typeof g===
        "undefined"){g=c;c={}}a=qa(a,c);h(a,g);return a}})("undefined"===typeof exports?esprima={}:exports);
(function(){var N,V,ha,W,da,e,R,ja,ea,ca,o,T,Z;function E(d){var r;try{r=new ActiveXObject("Msxml2.XMLHTTP")}catch(i){try{r=new ActiveXObject("Microsoft.XMLHTTP")}catch(m){r=U}}!r&&"undefined"!=typeof XMLHttpRequest&&(r=new XMLHttpRequest);r.open("GET",d,U);r.send(M);return r.responseText}function O(d){var r=[],d=d.replace("\\","/").split("/"),i;for(i in d)".."==d[i]?r.pop():r.push(d[i]);return r.join("/")}function j(){var J={b:{},n:{},m:{},depth:-1};J.b[N+"$"]={type:d.a,name:"",i:{}};return J}function H(){var d,
    r,e,m,o,j=arguments[0]||{},L=1,t=arguments.length,g=U;"boolean"===typeof j&&(g=j,j=arguments[1]||{},L=2);"object"!==typeof j&&"function"!==i(j)&&(j={});t===L&&(j=this,--L);for(;L<t;L++)if((d=arguments[L])!=M)for(r in d)e=j[r],m=d[r],j!==m&&(g&&m&&(y(m)||(o="array"===i(m)))?(o?(o=U,e=e&&"array"===i(e)?e:[]):e=e&&y(e)?e:{},j[r]=H(g,e,m)):m!==s&&(j[r]=m));return j}function i(d){return d==M?""+d:ma[$.call(d)]||"object"}function y(d){if(!d||"object"!==i(d)||d.nodeType||d&&"object"===typeof d&&"setInterval"in
    d)return U;try{if(d.constructor&&!Y.call(d,"constructor")&&!Y.call(d.constructor.prototype,"isPrototypeOf"))return U}catch(r){return U}for(var e in d);return e===s||Y.call(d,e)}function X(){aa&&P.apply(M,arguments)}function F(d,e){for(var i in e)d[i]=e[i]}function ka(d,e){F(d.b,e.b);F(d.n,e.n);F(d.m,e.m);d.depth=e.depth;return d}function ga(d){return d+"$"}function P(d,e,i,m,o,j){switch(arguments.length){case 1:console.log(d);break;case 2:console.log(d,e);break;case 3:console.log(d,e,i);break;case 4:console.log(d,
    e,i,m);break;case 5:console.log(d,e,i,m,o);break;default:console.log(arguments)}}function la(d){for(var d=d.split(/(\\|\/)/),e="",i=0;i<d.length-1;++i)if(d[i].length&&(!("/"==d[i]||"\\"==d[i])||!e.length))e+=d[i]+("/"!=d[i]?"/":"");return("/"==d[0]||"\\"==d[0]?"/":"")+e}var aa=U,oa="_"+(new Date).getTime(),ma={},$=Object.prototype.toString,Y=Object.prototype.hasOwnProperty;(function(){for(var d="Boolean,Number,String,Function,Array,Date,RegExp,Object".split(","),e=0,i=d.length;e<i;++e)ma["[object "+
    d[e]+"]"]=d[e].toLowerCase()})();var d=esprima.Va;V="Define";ha="Enum";W="Undef";da="Include";e="If";R="Endif";ja="Elseif";ea="Ifdef";ca="__";o="__FILE__";T="__LINE__";Z="__ARGS__";N="__FUNC__";var ba=[],na={ta:0},ia=0;(function(){function i(j,D,t,g,f,I){function v(a){$.push(F);F=a}function w(){F=$.length?$.pop():f}function S(){Y.push(a);a=x}function z(a){if(F&&D){switch(b.substr(-2,2)){case ";\n":return;case "}\n":a&&(b=b.substr(0,b.length-1)+";\n");return}h(";\n")}}function Q(a){return"//"+A+"// "+
    a}function y(){F&&h("\n")}function h(a){b+=a;I.ta++}function K(a){return a+"#"+I.ta}function q(a){var c=a.object;return c&&c.type==d.q?q(c):a}function k(a){for(var c=0;c<a.length;++c)n(a[c]),c!=a.length-1&&h(", ")}function G(a){function c(a){a.type==d.C||a.type==d.k||a.type==d.M||a.type==d.L||a.type==d.I?(h("("),n(a),h(")")):n(a)}if(!g){var b=ga(r(a,I)),k=t.b[b];if(k&&!k.i[K(b)]){k.i[K(b)]=1;n(k);return}var e=a.b,i;if(e.type==d.a)if(k=t.b[e.name+"$"])b=q(k),b.object&&b.object.name==ca&&(aa&&(i=r(a,
    I)),a.V=k.V,a.b=k.b,X(Q(i+" ==> "+r(a,I))));else if(i=b.substr(0,b.lastIndexOf("."))+".__$",(k=t.b[i])&&!k.i[K(i)]){t.b[b]=k;t.b[ca+"$"]={type:d.a,name:e.name,i:{}};n(a);delete t.b[ca+"$"];delete t.b[b];return}}v(U);k=a.object;a.V?(c(k),h("["),n(a.b),h("]")):(c(k),h("."),k=U,a.b.type==d.a&&(b=ga(r(a.b,I)),!g&&t.b[b]&&t.b[b].ua&&(k=x)),k?h(r(a.b,I)):n(a.b));w();z()}function C(c){if(a)S();else{c=c.arguments[0];try{eval(i(c,x,t,U,F,I))||S()}catch(d){p(d)}}}function l(b){var f=b.callee;if(f.type==d.a){switch(f.name){case R:a=
    Y.length?Y.pop():U;return;case ja:b.arguments.length&&p(Error("Parametric ElseIf unsupported!"));len=Y.length;if(!a||Y[len-1]===U)a=!a;return;case e:C(b);return;case ea:if(a)S();else{b=b.arguments[0];try{t.b[b.name+"$"]||S()}catch(q){p(q)}}return}if(a)return;switch(f.name){case da:if(!g&&(b=b.arguments,b.length)){b=b[0].value;ba.push(la(b));b=b.replace(/^.*[\\\/]/,"");""==b&&(b=Preprocessor.defaultInclude);var b=O(ba.join("")+b),l=t.m[b];l?l.Xa?console.warn("<include: "+b+"> already been used."):
    l.Ua?P("<include: "+b+"> skipped. "):(l.Xa=x,c=b,n(l),c=""):console.warn("<include: "+b+"> not found.");ba.pop()}return;case W:g||(b=b.arguments,l=r(b[0],I),b[0].type==d.l?(l=Preprocessor.j(b[0].callee,U),l+="+"+b[0].arguments.length,delete t.n[l]):delete t.b[l+"$"]);return;case V:case ha:return}}if(!a){if(!g){var m=r(f,I),l=m+"+"+b.arguments.length,o=t.n[l];if(o&&!o.i[K(l)]){var m=o.U,j=b.arguments,u,D,A,y;if(m.length==j.length){++t.depth;A={};y={};o.i[K(l)]=1;u=t.b;for(f=0;f<m.length;++f){D=m[f].Wa;
    var B=m[f].name+"$";if(u[B]){if(0<t.depth){var E=ga(r(j[f],I));j[f]=H(x,{},u[E])}else E=Q("::erase arg <"+m[f].name+"> ("+r(u[B],I)+" ==> "+r(j[f],I)+") in call: "+l),console.warn(E);A[B]=u[B]}else A[B]=M;E=j[f];D&&(E={type:d.g,value:i(j[f],U,t,U,F,I)});y[B]=E;y[B].i={}}for(f in y)u[f]=y[f];l=i(o.rel.body.body,x,t,U,F,I);for(f in A)A[f]!=M?u[f]=A[f]:delete u[f];X(Q(r(b,I)+" ==> "+l));--t.depth;h(l);return}}else if(l=m+"+*",(o=t.n[l])&&!o.i[K(l)]){l="";for(f=0;f<b.arguments.length;++f)l+=i(b.arguments[f],
    U,t,U,F,I),f+1!==b.arguments.length&&(l+=",");l=l.match(/^\s*$/)?{type:d.a,name:"undefined"}:esprima.parse(l).body[0];l.i={};t.b[Z+"$"]=l;b=i(o.rel.body.body,x,t,U,F,I);delete t.b[Z+"$"];h(b);return}if(!ia&&(o=l.substr(0,l.lastIndexOf(".")),m=o+".__+"+b.arguments.length,j=t.n[o+".__+*"],(o=t.n[m])&&!o.i[K(m)]||j&&!j.i[K(j)])){t.n[l]=o?o:j;B=ca+"$";t.b[B]={type:d.a,name:f.b.name,i:{}};n(b);delete t.b[B];return}}b.callee.type!=d.p?(v(U),n(b.callee),h("("),k(b.arguments),h(")"),w()):(h("("),n(b.callee),
    h(")"),h("("),v(U),k(b.arguments),w(),h(")"));z()}}function u(a,c){c||U||h("function");h("(");v(U);k(a.r);w();h(")");v(x);n(a.body);w()}function B(a){function c(a){a.type==d.R?(h("("),n(a),h(")")):n(a)}v(U);h("(");n(a.test);h("? ");c(a.s);h(" : ");c(a.w);h(")");w();z()}function n(b){if(b)if(b instanceof Array)for(var f=0;f<b.length;++f)n(b[f]);else if(a)b.type==d.l?l(b):b.type==d.G&&(n(b.c),z(1));else switch(b.type){case d.C:v(U);n(b.left);h(" "+b.d+" ");n(b.right);w();z();break;case d.B:h("[");v(U);
    k(b.elements);w();h("]");z();break;case d.X:h(" {\n");v(x);n(b.body);h("\n}\n");w();break;case d.k:v(U);var f=b.left.type,e=b.right.type;f==d.a||f==d.g?n(b.left):(h("("),n(b.left),h(")"));h(" "+b.d+" ");e==d.a||e==d.g?n(b.right):(h("("),n(b.right),h(")"));w();z();break;case d.D:h("break ");v(U);n(b.label);w();z();break;case d.l:l(b);break;case d.Z:h("catch");h("(");v(U);n(b.za);w();h(")");v(x);n(b.body);w();break;case d.$:B(b);break;case d.F:h("continue ");v(U);n(b.label);w();z();break;case d.ba:h("do");
    v(x);n(b.body);w();h("while");h("(");v(U);n(b.test);w();h(")");y();break;case d.aa:h("debugger");z();break;case d.ca:z();break;case d.G:n(b.c);z(1);break;case d.ea:h("for ");v(U);h("(");n(b.A);h("; ");n(b.test);h("; ");n(b.update);h(")");w();v(x);n(b.body);w();y();break;case d.da:h("for ");v(U);h("(");n(b.left);h(" in ");n(b.right);h(")");w();v(x);n(b.body);w();y();break;case d.H:E++;var f=N+"$",e=b.id,j=t.b[f].name;e.type===d.a&&(t.b[f].name=e.name);h("function ");v(U);n(b.id);w();h("(");v(U);k(b.r);
    w();h(")");v(x);n(b.body);w();y();t.b[f].name=j;E--;break;case d.p:E++;u(b);E--;break;case d.a:a:{f=b.name;if(!g&&(e=f+"$",(j=t.b[e])&&!j.i[K(e)])){j.i[K(e)]=1;if(j.type!=d.q){X(Q(r(b,I)+" ==> "+r(j,I)));j.type!=d.a&&j.type!=d.H&&j.type!=d.p&&j.type!=d.Q&&j.type!=d.B&&j.type!=d.l&&j.type!=d.g?e==Z+"$"?n(j):(h("("),n(j),h(")")):n(j);break a}if(q(j).object.name!=ca){n(j);break a}}f==o?h('"'+c+'"'):f==T?h('""'):h(f);z()}break;case d.fa:v(U);h("if (");n(b.test);h(")");w();v(x);n(b.s);b.w&&(h("else "),
    n(b.w));w();y();break;case d.g:"string"==typeof b.value?(b=(""+b.value).replace(/\\"/g,'"').replace(/"/g,'\\"').replace(/\n/g,""),h('"'+b+'"')):h(b.value);z();break;case d.ga:f=b.label;v(U);n(f);h(":\n");n(b.body);w();break;case d.I:f=b.left.type;e=b.right.type;v(U);f==d.a||f==d.g?n(b.left):(h("("),n(b.left),h(")"));h(" "+b.d+" ");e==d.a||e==d.g?n(b.right):(h("("),n(b.right),h(")"));w();z();break;case d.q:m++;G(b);m--;break;case d.P:h("new ");v(U);f=b.callee;g?(f.type==d.a||f.type==d.q?n(f):(h("("),
    n(f),h(")")),h("("),k(b.arguments),h(")")):(e=i(f,U,t,U,U,I),f.type!=d.a&&f.type!=d.q&&(e="("+e+")"),b=H(x,{},b),b.callee={type:d.a,name:e},b.type=d.l,n(b));w();z();break;case d.Q:f=b.Ba;h(" {");v(U);for(e=0;e<f.length;++e)(j=f[e].O)?"get"==j||"set"==j?(f[e].value.type!=d.p&&p(Error("unsupported getter")),h(j+" "),n(f[e].key),h(" "),u(f[e].value,x)):(P(b),p(Error("unsupported <kind: "+j+"> of object member"))):(n(f[e].key),h(": "),n(f[e].value)),e!=f.length-1&&h(", ");w();h("}");z();break;case d.ia:n(b.body);
    break;case d.J:h("return ");v(U);n(b.h);w();z();break;case d.R:v(U);k(b.ra);w();break;case d.S:h("switch");h("(");v(U);n(b.qa);w();h(")");h(" {");n(b.wa);h("}");y();break;case d.ja:v(U);b.test==M?h("\ndefault:\n"):(h("\ncase "),n(b.test),h(":\n"));w();v(x);n(b.s);w();z();break;case d.ka:h("this");break;case d.la:h("throw ");n(b.h);z();break;case d.ma:h("try");v(x);n(b.va);n(b.Sa);b.xa&&(h("finally"),n(b.xa));w();z();break;case d.L:h(b.d);1<b.d.length&&h(" ");f=b.h.type;v(U);f==d.a||f==d.g?n(b.h):
    (h("("),n(b.h),h(")"));w();z();break;case d.M:b.prefix&&h(b.d);v(U);n(b.h);w();b.prefix||h(b.d);z();break;case d.N:b=b.W;h("var ");v(U);for(f=0;f<b.length;++f)e=b[f],n(e.id),e.A&&(h("="),n(e.A)),f!=b.length-1&&h(", ");w();z(x);break;case d.na:h("while ");h("(");v(U);n(b.test);w();h(")");v(x);n(b.body);w();break;case d.oa:h("with ");h("(");v(U);n(b.object);w();h(")");v(x);n(b.body);w();break;default:console.log("TODO: unsupported code structure"),P(b)}}var D=D===s?x:D,g=g===s?x:g,t=t||M,A=aa?Math.floor(1E6*
    Math.random()):"",a=U,f=f===s?x:f,c="",b="",F=f,$=[],Y=[];n(j);return b}function r(d,e){return i(d,U,M,x,x,e)}var E=0,m=0,D=j();Preprocessor.j=function(d,e,m,g,f){g===x&&(D=j());m&&(D=ka(D,m),m.b[N+"$"]||delete D.b[N+"$"]);na.ta++;return i(d,e,D,m?U:x,f,na)}})();(function(){function i(){t.push(L);L=x}function o(g){ia++;var g=g.arguments,f=Preprocessor.j(g[0],U);if(g[0].type==d.l){var f=Preprocessor.j(g[0].callee,U),e=g[0].arguments.length,i=f.replace(/\./g,"_")+"_"+e+oa;if(F){var m=j();if(1===e&&
    g[0].arguments[0].name===Z)f+="+*";else for(var f=f+("+"+e),r=0;r<e;++r){var t=g[0].arguments[r],y=t.name;"$$"==y.substr(0,2)&&(y=y.substr(2),t.Wa=x);t.name=i+"_"+y;t.i={};m.b[y+"$"]=t}delete m.b[N+"$"];e=Preprocessor.j(g[1].body,x,m,x,x);try{g[1].body.body=esprima.parse(e).body[0].body}catch(E){P("error after function modification, param name replacing..."),P(Preprocessor.j(g[1].body,x,M,x,x)),P(e),P(m),p(E)}}D.n[f]={U:g[0].arguments,rel:g[1],i:{},ua:2<g.length}}else f+="$",D.b[f]=g[1],D.b[f].i=
{},D.b[f].ua=2<g.length;ia--}function y(d){if(L)i();else{d=d.arguments[0];try{eval(Preprocessor.j(d,x,D,U))||i()}catch(f){P("cannot eval If() statament with ignore: "+L),P(D),P("value:"),P(Preprocessor.j(d,x,D,U)),p(f)}}}function m(g){if(g)if(g instanceof Array)for(var f=0;f<g.length;++f)m(g[f]);else switch(g.type){case d.C:m(g.left);m(g.right);break;case d.B:m(g.elements);break;case d.X:m(g.body);break;case d.k:m(g.left);m(g.right);break;case d.D:break;case d.l:a:{var j=g.callee;if(j&&j.type==d.a){if(j.name==
    ja){if(g.arguments.length&&p(Error("Parametric ElseIf unsupported!")),len=t.length,!L||t[len-1]===U)L=!L}else j.name==R&&(L=t.length?t.pop():U);if(j.name==e)y(g);else if(j.name==ea)if(L)i();else{var v=g.arguments[0];try{D.b[v.name+"$"]||i()}catch(w){p(w)}}if(L)break a;if(j.name==V)o(g);else if(j.name!=W)if(j.name==ha){var S=g.arguments;if(!(2>S.length)){var z=S[0];if(z.type==d.B){var Q=0,j=U,N,v={type:d.l,callee:{type:d.a,name:V},arguments:[M,{type:d.g,value:0}]},h=M,K;2<S.length&&(h=Preprocessor.j(S[2],
    U));for(var z=z.elements,q=0,k;q<z.length;++q){S=U;k=H(x,{},v);z[q].type==d.C?(S=x,K=z[q].left,z[q].right.type===d.g&&"string"===typeof z[q].right.value?(f=z[q].right.value,(N=f.match(/^(.*?\w)(\d+)$/i))?(f=N[1],Q=Number(N[2])):Q=0,j=f):(j=M,Q=Number(Preprocessor.j(z[q].right,U,D)))):K=z[q];if(h)try{K=esprima.parse(h+"."+Preprocessor.j(K,U)).body}catch(G){p(G)}j===M?(k.arguments[0]=K,k.arguments[1].value=Q):(N&&(f+=Q),S||(f=j+Q),k.arguments[0]=K,k.arguments[1].value=f);Q++;X("//"+("Enum: "+Preprocessor.j(K,
    U)+" : "+f));o(k)}}}}else if(j.name==da)b:if(f=g.arguments,f.length){f=f[0].value;ba.push(la(f));f=f.replace(/^.*[\\\/]/,"");""==f&&(f=Preprocessor.defaultInclude);f=O(ba.join("")+f);if(!D.m[f]){try{z=E(f)}catch(C){C instanceof SyntaxError||p(C)}if(!z.length)break b;try{Q=esprima.parse(z)}catch(l){P("ERROR:: syntax error in: "+f),p(l)}D=Preprocessor.pa(Q,D,F);D.m[f]=Q.body}ba.pop()}}else m(g.callee);m(g.arguments)}break;case d.Z:m(g.za);m(g.Ra);m(g.body);break;case d.$:m(g.test);m(g.s);m(g.w);break;
    case d.F:break;case d.ba:m(g.body);m(g.test);break;case d.aa:break;case d.ca:break;case d.G:m(g.c);break;case d.ea:m(g.A);m(g.test);m(g.update);m(g.body);break;case d.da:m(g.left);m(g.right);m(g.body);break;case d.H:m(g.r);m(g.body);break;case d.p:m(g.r);m(g.body);break;case d.a:break;case d.fa:m(g.test);m(g.s);m(g.w);break;case d.g:break;case d.ga:m(g.body);break;case d.I:m(g.left);m(g.right);break;case d.q:m(g.object);break;case d.P:m(g.arguments);break;case d.Q:g=g.Ba;for(f=0;f<g.length;++f)m(g[f].key),
        m(g[f].value);break;case d.ia:m(g.body);break;case d.J:m(g.h);break;case d.R:m(g.ra);break;case d.S:m(g.qa);m(g.wa);break;case d.ja:m(g.test);m(g.s);break;case d.ka:break;case d.la:m(g.h);break;case d.ma:m(g.va);break;case d.L:m(g.h);break;case d.M:m(g.h);break;case d.N:g=g.W;for(f=0;f<g;++f)m(g[f].id),m(g[f].A);break;case d.na:m(g.test);m(g.body);break;case d.oa:m(g.object);m(g.body);break;default:console.log("unknown syntax structure founded:"),console.log(g)}}var D,F,L,t=[];Preprocessor.pa=function(d,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   f,e){L=U;t=[];F=e===s?x:e;X("SubstArg: "+F);e=j();D=f?ka(e,f):e;m(d);return D};Preprocessor.code=function(d,f){aa=Preprocessor.debug;ba=[];try{var e=esprima.parse(d)}catch(j){p(j)}var i=Preprocessor.pa(e);Preprocessor.next=function(d){if("object"==typeof d&&d.m)for(var g in d.m)d.m[g]===U&&(i.m[g].Ua=x);X("=====> reflect starting...");X(i);return Preprocessor.j(e,x,i,x)};if("object"==typeof f){var m={};if(f.m){var o=m.m={},r;for(r in i.m)o[r]=x}return m}return Preprocessor.next()};Preprocessor.file=
    function(d){return Preprocessor.code(E(d))};Preprocessor.watch=function(){var d=document.getElementsByTagName("script"),f="",e;for(e in d){var i=d[e];i.type==Preprocessor.scriptType&&(i.src&&(f+=E(i.src)),f+=i.innerHTML)}d=document.getElementsByTagName("head")[0];script=document.createElement("script");script.type="text/javascript";script.innerHTML=Preprocessor.code(f);script.id="akra-js-"+(new Date).getTime();d.appendChild(script)};Preprocessor.extractMacro=function(d){var f;try{f=esprima.parse(d)}catch(e){P("esprima parse error: "),
    p(e)}Preprocessor.pa(f,M,U);var d="",i;for(i in D.b)d+=("Define("+i.substr(0,i.length-1)+","+Preprocessor.j(D.b[i],x,0,0,U)+")").replace(/(\r\n|\n|\r)/gm,"")+"\n";for(i in D.n){f=D.n[i];for(var j="",j=j+("Define("+i.substr(0,i.lastIndexOf("+"))+"("),m=0;m<f.U.length;++m)j+=Preprocessor.j(f.U[m],U)+(m!=f.U.length-1?",":"");j+="),function()"+Preprocessor.j(f.rel.body,x,0,0,U)+")";d+=j.replace(/(\r\n|\n|\r)/gm,"")+"\n"}return d};Preprocessor.extractFileMacro=function(d){return this.Za(E(d))};Preprocessor.watch()})()})("undefined"===
    typeof exports?Preprocessor={defaultInclude:"Include.js",debug:U,scriptType:"text/akra-js",keywords:{}}:exports);